// Pure transformation: OpenAPI contract object -> API Gateway import document.
// Used by scripts/render-gateway-spec.mjs (I/O) and unit-tested directly.
//
// Injects Lambda proxy integrations, request validators, the Cognito
// authorizer, CORS preflight and problem+json gateway responses. Placeholders
// ${lambda_invoke_arn}, ${cognito_user_pool_arn} and ${cors_origin} are
// substituted by Terraform's templatefile() at apply time.
import { stringify } from "yaml";

export function renderGatewaySpec(input) {
  const spec = structuredClone(input);
  const METHODS = ["get", "post", "put", "patch", "delete"];
  const lambdaIntegration = () => ({
    type: "aws_proxy",
    httpMethod: "POST",
    uri: "${lambda_invoke_arn}",
    passthroughBehavior: "when_no_match",
  });

  // Request validators: validate body + params for every operation.
  spec["x-amazon-apigateway-request-validators"] = {
    all: { validateRequestBody: true, validateRequestParameters: true },
  };
  spec["x-amazon-apigateway-request-validator"] = "all";

  // Turn the bearer scheme into a Cognito user-pools authorizer.
  spec.components ??= {};
  spec.components.securitySchemes ??= {};
  spec.components.securitySchemes.cognito_jwt = {
    type: "apiKey",
    name: "Authorization",
    in: "header",
    "x-amazon-apigateway-authtype": "cognito_user_pools",
    "x-amazon-apigateway-authorizer": {
      type: "cognito_user_pools",
      providerARNs: ["${cognito_user_pool_arn}"],
    },
  };

  const corsAllowHeaders = "'authorization,content-type,x-api-key,idempotency-key'";
  const corsOrigin = "'${cors_origin}'";

  for (const [, item] of Object.entries(spec.paths)) {
    const methodsPresent = ["OPTIONS"];
    for (const method of METHODS) {
      if (!item[method]) continue;
      methodsPresent.push(method.toUpperCase());
      // A fresh object per operation so the YAML has no anchors/aliases.
      item[method]["x-amazon-apigateway-integration"] = lambdaIntegration();
    }

    // CORS preflight via a mock integration, advertising exactly the methods this
    // path serves. An author-written OPTIONS operation in the contract wins.
    const corsHeaders = {
      "Access-Control-Allow-Origin": corsOrigin,
      "Access-Control-Allow-Methods": `'${methodsPresent.join(",")}'`,
      "Access-Control-Allow-Headers": corsAllowHeaders,
    };
    item.options ??= {
      summary: "CORS preflight",
      security: [],
      responses: {
        204: {
          description: "CORS headers",
          headers: Object.fromEntries(
            Object.keys(corsHeaders).map((h) => [h, { schema: { type: "string" } }]),
          ),
        },
      },
      "x-amazon-apigateway-integration": {
        type: "mock",
        requestTemplates: { "application/json": '{"statusCode": 204}' },
        responses: {
          default: {
            statusCode: "204",
            responseParameters: Object.fromEntries(
              Object.entries(corsHeaders).map(([h, v]) => [`method.response.header.${h}`, v]),
            ),
          },
        },
      },
    };
  }

  // Errors generated by API Gateway itself (authorizer, api-key, validator,
  // throttling, size limits) never reach the Lambda. Without these they would be
  // `{"message": "..."}` with no CORS headers; with them every error the client
  // can see is the contract's RFC 7807 problem+json and carries the CORS origin.
  const problemTemplate = (status, title, detail) =>
    JSON.stringify({
      type: "about:blank",
      title,
      status,
      detail,
      request_id: "$context.requestId",
    });
  const gatewayResponse = (status, title, detail) => ({
    statusCode: String(status),
    responseParameters: {
      "gatewayresponse.header.Access-Control-Allow-Origin": corsOrigin,
      "gatewayresponse.header.Access-Control-Allow-Headers": corsAllowHeaders,
      "gatewayresponse.header.x-request-id": "context.requestId",
    },
    responseTemplates: {
      "application/json": problemTemplate(status, title, detail),
      "application/problem+json": problemTemplate(status, title, detail),
    },
  });
  spec["x-amazon-apigateway-gateway-responses"] = {
    DEFAULT_4XX: gatewayResponse(400, "Bad Request", "$context.error.messageString"),
    DEFAULT_5XX: gatewayResponse(500, "Internal Server Error", "An unexpected error occurred"),
    BAD_REQUEST_BODY: gatewayResponse(400, "Bad Request", "$context.error.validationErrorString"),
    BAD_REQUEST_PARAMETERS: gatewayResponse(
      400,
      "Bad Request",
      "$context.error.validationErrorString",
    ),
    UNAUTHORIZED: gatewayResponse(401, "Unauthorized", "Missing or invalid credentials"),
    EXPIRED_TOKEN: gatewayResponse(401, "Unauthorized", "Token has expired"),
    INVALID_SIGNATURE: gatewayResponse(401, "Unauthorized", "Token signature is invalid"),
    MISSING_AUTHENTICATION_TOKEN: gatewayResponse(
      401,
      "Unauthorized",
      "Missing or invalid credentials",
    ),
    ACCESS_DENIED: gatewayResponse(403, "Forbidden", "Access denied"),
    INVALID_API_KEY: gatewayResponse(403, "Forbidden", "Missing or invalid API key"),
    WAF_FILTERED: gatewayResponse(403, "Forbidden", "Request blocked"),
    REQUEST_TOO_LARGE: gatewayResponse(413, "Payload Too Large", "Request body exceeds the limit"),
    THROTTLED: gatewayResponse(429, "Too Many Requests", "Rate limit or quota exceeded"),
    QUOTA_EXCEEDED: gatewayResponse(429, "Too Many Requests", "Rate limit or quota exceeded"),
  };
  return spec;
}

// YAML for the rendered spec: no anchors/aliases, so every operation carries
// its own integration block and diffs stay readable.
export function stringifyGatewaySpec(spec) {
  return stringify(spec, { aliasDuplicateObjects: false });
}
