#!/usr/bin/env node
// Renders every api/*.odcs.yaml data contract into a runtime validator module
// under packages/contracts/src/generated/odcs/ (see scripts/lib/odcs-zod.mjs).
// Regenerated by `task gen`; never edit the output by hand.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parse } from "yaml";
import { readOdcs, renderOdcsModule } from "./lib/odcs-zod.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "packages/contracts/src/generated/odcs");
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const files = readdirSync(join(root, "api"))
  .filter((f) => f.endsWith(".odcs.yaml"))
  .sort();
const modules = [];
for (const file of files) {
  const contract = parse(readFileSync(join(root, "api", file), "utf8"));
  const { id } = readOdcs(contract);
  writeFileSync(join(outDir, `${id}.ts`), renderOdcsModule(contract));
  modules.push(id);
}
writeFileSync(
  join(outDir, "index.ts"),
  modules.map((id) => `export * from "./${id}.js";`).join("\n") + "\n",
);
console.log(
  `Generated ${modules.length} ODCS validator module(s) in packages/contracts/src/generated/odcs/`,
);
